### ISSUE TITLE
Transformed triangle mesh render incorrectly

### ISSUE THREAD

**Issue by nidin** [fogleman/pt#12]
Transformed triangle mesh render incorrectly
seems like normal calculations are wrong.

**Scale = 1**
![image](https://cloud.githubusercontent.com/assets/198246/13755469/a4797296-ea1b-11e5-9bb1-a17b54f9e3ef.png)

**Scale = 0.9**
![image](https://cloud.githubusercontent.com/assets/198246/13755501/d753f434-ea1b-11e5-82c4-c7900e78d566.png)

**Comment by fogleman** [comment]
Nice catch, thanks! For some reason, translating and rotating worked but not scaling.

Fixed with aac95259dbc79b708cbd1d4e726b81407bb73475

Also added examples/ellipsoid.go to verify non-uniform scaling.

**Comment by fogleman** [comment]
Found a couple more issues and fixed them. Here's a before & after of the new example.

Before:

![1](https://cloud.githubusercontent.com/assets/520208/13766731/edeed56e-ea3a-11e5-87e6-0f12d69cafdd.png)

After:

![2](https://cloud.githubusercontent.com/assets/520208/13766732/f3a46d20-ea3a-11e5-83bf-ee3d4e353633.png)

**Comment by ghost** [comment]
First: what editor used? 
Second: I found way to run examples... even 32-bit.

**Comment by nidin** [comment]
@acterhd If the first question is for me, Answer is WebStorm.
and good that you found a way to run examples :+1:
