### ISSUE TITLE
Will OpenGL version of this PT?

### ISSUE THREAD

**Issue by ghost** [fogleman/pt#13]
Hello. Will you development OpenGL (or Vulkan) version of this good PT? 
I tried to build octree with hardware rasterization (and atomics), and acheive not so bad speed (interactive) with 20k polygons. Even If rebuild octree. Tested only for Nvidia, but now I have option for non-conservative (and slower) method of voxelization. 
https://github.com/acterhd/ogl-reflections

**Comment by fogleman** [comment]
Very cool. :)

I think pt will remain Go-based only. Switching to OpenGL would be a complete rewrite, a whole new project.

**Comment by ghost** [comment]
Also... (but old project)
https://github.com/go-gl/gl

**Comment by fogleman** [comment]
I know, I've used it before. :)
