### ISSUE TITLE
Submit gopher rendering to golang-graphics repository

### ISSUE THREAD

**Issue by mholt** [fogleman/pt#2]
Would you be alright with me submitting your rendered gopher as a PNG to the [golang-graphics](https://github.com/mholt/golang-graphics) repository? Of course you'd be duly credited and the original .obj file would be referenced as well (which I also would like to add to the repo).

**Comment by fogleman** [comment]
Sure!

**Comment by mholt** [comment]
Great, thanks! I'll get around to it this weekend.
